# Generated by Django 4.1 on 2022-08-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedCSV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "_uploaded_csv",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=512, null=True)),
                ("level1", models.CharField(blank=True, max_length=255, null=True)),
                ("level2", models.CharField(blank=True, max_length=255, null=True)),
                ("level3", models.CharField(blank=True, max_length=255, null=True)),
                ("price", models.CharField(blank=True, max_length=255, null=True)),
                ("price_sp", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                ("properties", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shared_purchases",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unit", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                (
                    "show_on_main",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "uploaded_csv_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="csv_parser.uploadedcsv",
                    ),
                ),
            ],
            options={
                "db_table": "_products",
            },
        ),
    ]
